# Material for MkDocs STYLE GUIDE configuration file

# Project information
site_name: 'Status writing style guide'
site_url: https://write.status.im/
site_author: 'Status Research & Development GmbH'
site_description: 'Status docs writing style guide'

# Project directories
docs_dir: '../../docs/'
site_dir: '../../generated/'

# Repository
repo_name: 'Status docs style guide'
repo_url: https://github.com/status-im/write.status.im
edit_uri: edit/develop/docs/style-guide

# Copyright
copyright: 'Status Research & Development GmbH'

# Theme configuration
theme:
    name: material
    custom_dir: '../../overrides/'
    logo: assets/images/status-logo-320x320.png
    favicon: assets/images/status-logo-32x32.png             # Status favicon
    language: en
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: grey
        accent: deep orange
        toggle:
          icon: material/weather-night 
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: grey
        accent: deep orange
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
    font:
      text: Inter
      code: Roboto Mono
    icon:
      repo: fontawesome/brands/github

      # Custom admonitions (callouts) require "Insiders" subscription
      admonition:
        # note: fontawesome/solid/note-sticky
        info: fontawesome/solid/circle-info
        tip: fontawesome/solid/wand-magic-sparkles
        # success: fontawesome/solid/circle-check
        # question: fontawesome/solid/question-circle
        warning: fontawesome/solid/triangle-exclamation
        # failure: fontawesome/solid/bomb
        # danger: fontawesome/solid/skull
        # bug: fontawesome/solid/robot

    # Material for MkDocs features
    features:
      - search.suggest
      - search.highlight
      - navigation.instant
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.indexes
      - navigation.top
      - navigation.tracking

# Extensions
markdown_extensions:
  - meta
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3
      permalink: true

# Theme customization
extra_css:
  - assets/stylesheets/extra.css

# Transaltions (intentionally disabled)
extra:
  # Footer icons and links
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ethstatus
      name: Status on Twitter
    - icon: material/web
      link: https://status.im
      name: Status website
    - icon: material/chat
      link: https://join.status.im/chat/public/status

# Plugins
plugins:
  - search:                                         
      lang: en
  - git-committers:
      docs_path: docs/
      repository: status-im/write.status.im
      branch: master
  - git-revision-date
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

# Page tree (for mobile view)
nav:
  - Welcome: index.md
  - Style guidelines: style-guidelines.md
  - Structuring the content: structuring-the-content.md
  - Style conventions: style-conventions.md
